**ChatGPT is forbidden**

**Data generation**

Create and visualize arrays containing only real numbers, then integers, then strings, then a mix of integers and strings

In [6]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.24.4
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

In [7]:
import numpy as np
arr1=np.array([1,2,3,4,5,6],dtype=np.float64)
print('with real numbers: ',arr1)
arr2=np.array([1,2,3,4,5,6],dtype=np.int64)
print('with integers: ',arr2)
arr3=np.array([1,2,3,4,5,6],dtype='<U12')
print('with strings: ',arr3)
arr4=np.array([[1,2,1],['s','t','r']])
print('combined: \n',arr4)


with real numbers:  [1. 2. 3. 4. 5. 6.]
with integers:  [1 2 3 4 5 6]
with strings:  ['1' '2' '3' '4' '5' '6']
combined: 
 [['1' '2' '1']
 ['s' 't' 'r']]


Add two arrays made of integers, element by element (the two arrays must be the same size)

In [8]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(a1)
print(a2)
print('added: ',np.add(a1,a2))

[1 2 3]
[4 5 6]
added:  [5 7 9]


Create a 3*3 array including only zeros on the first line, then 1s on the second line, then the number 5 on the third line

In [9]:
a3=np.zeros((3,3))
a3[1,:]=[1,1,1]
a3[2,2]=5
print(a3)

[[0. 0. 0.]
 [1. 1. 1.]
 [0. 0. 5.]]


Extract the shape attribute from this array

In [10]:
a3.shape

(3, 3)

Create an array of 3 by 3 by 3 including only real numbers chosen from a normal distribution

In [11]:
arr3D=np.random.normal(size=(3, 3, 3))
#print(arr3D)
arr3D

array([[[ 0.23857999, -0.17846653,  0.15208775],
        [-0.37266978,  0.47564352, -1.33058033],
        [ 1.69865713, -1.38254631, -0.55847457]],

       [[-0.31642584, -0.89199308,  0.40480313],
        [ 0.39093525, -0.27373202,  0.40544136],
        [ 0.43311498,  0.50597459, -0.267677  ]],

       [[ 0.37977517, -0.23173228,  0.45512975],
        [ 1.24932793,  0.19009863,  0.68028901],
        [ 0.13420624, -0.40704686, -0.4138156 ]]])

Create a vector comprising 7 equally spaced values, between 2 and 3

In [12]:
vect=np.linspace(2,3,num=7)
vect

array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333, 3.        ])

Use the choice function to sample 5 values ​​from this last vector, once with replacement, and once without replacement

In [13]:
sample1=np.random.choice(vect,5)
print('Sample with replacement: ')
print(sample1)
sample2=np.random.choice(vect,5,replace=False)
print('Sample without replacement: ')
print(sample2)

Sample with replacement: 
[2.33333333 2.16666667 3.         3.         2.66666667]
Sample without replacement: 
[2.66666667 2.         2.16666667 2.33333333 2.5       ]


Create a vector corresponding to a sequence of numbers, from 13 to 19, counting in steps of one

In [14]:
vect2=np.arange(13,20,1)
vect2

array([13, 14, 15, 16, 17, 18, 19])

Create a 5*5 identity matrix

In [15]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Create a 5*5 matrix of zeros, with 1 on the diagonal. Then specifically extract this diagonal

In [16]:
idmatrix=np.identity(5)
np.diag(idmatrix)

array([1., 1., 1., 1., 1.])

Complete this NumPy line to determine if the elements of a vector are finite (not infinite or not
a number)

In [17]:
a = np.array([1, 0, np.nan, np.inf]) 
print(np.isfinite(a))

[ True  True False False]


Complete this NumPy program to test element by element if it corresponds to infinity (positive
or negative)

In [18]:
np.array([1, 0, np.nan, np.inf])
print(np.isinf(np.array([1, 0, np.nan, np.inf])))

[False False False  True]


Complete this NumPy program to perform a comparison by element (equal, then equal to
a certain tolerance) of two given tables

In [19]:
x = np.array([72, 79, -135, 120, -10, 60, 100])
y = np.array([72, 79, -135, 120, -10, 60, 100.01])
print(np.equal(x, y))
print(np.allclose(x, y,rtol=0.05))

[ True  True  True  True  True  True False]
True


**Subsetting & reshaping**

Create an array of 7 by 7 including only real numbers chosen from a normal distribution, then select only the first row, the first column, all columns up to the third, and the element of the second column and third row

In [20]:
arr7=np.random.normal(size=(7,7))
print(arr7[0,:])
print(arr7[:,0])
print(arr7[:,:3])
print(arr7[2,1])

[-0.88833679  1.00717848 -0.84959079 -0.79641808 -1.94697522  1.42799321
  0.65172549]
[-0.88833679  0.42818381 -0.99938002  2.01782965  0.03155094  0.03082673
 -0.57264899]
[[-0.88833679  1.00717848 -0.84959079]
 [ 0.42818381 -0.18594562  0.89324993]
 [-0.99938002  1.03413618  1.87051381]
 [ 2.01782965  1.12127106  0.63634687]
 [ 0.03155094  1.36360816 -0.14719208]
 [ 0.03082673  0.07698304  0.60115831]
 [-0.57264899 -0.42605672  1.67661707]]
1.0341361820251755


Create an array that is the repetition of one 1, two 2s, and three 3s, then from this vector, create a new array including the "unique" values ​​(i.e., 1, 2, and 3)

In [21]:
arr4=np.array([1,2,2,3,3,3])
new_arr4=np.unique(arr4)
new_arr4

array([1, 2, 3])

Créez un array de 5*5 comprenant des chiffres entiers choisis aléatoirement, puis réalisez une transposition de cette matrice

In [22]:
arr5=np.random.randint(100,size=(5,5))
print(arr5)
print(np.transpose(arr5))

[[32 31 50 76  8]
 [ 3 53 27 10  1]
 [48 42 95 18 40]
 [92 90  7 51 31]
 [51 19 71 19 23]]
[[32  3 48 92 51]
 [31 53 42 90 19]
 [50 27 95  7 71]
 [76 10 18 51 19]
 [ 8  1 40 31 23]]


Create a vector of 25 successive integers, then use reshape to make it a 5*5 matrix. Then play with the reshape function to illustrate how it works

In [23]:
vect3=np.arange(1,26)
np.reshape(vect3,newshape=(5,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Make a broadcast of two arrays of your design

In [24]:
print('first array: ',arr1)
print('second array: ',arr2)
print('result:')
arr1*arr2

first array:  [1. 2. 3. 4. 5. 6.]
second array:  [1 2 3 4 5 6]
result:


array([ 1.,  4.,  9., 16., 25., 36.])

Illustrate “type casting” by changing the data type contained in an array of your choice

In [25]:
arr_int=np.array([1,2,3,8,7,50])
arr_int.astype(dtype=np.float32)

array([ 1.,  2.,  3.,  8.,  7., 50.], dtype=float32)

Create a 4*4 array including integers, which you will cut in half using vsplit

In [26]:
arr4D=np.random.randint(100,size=(4,4))
print('original array: \n',arr4D)
print('new arrays: \n',np.vsplit(arr4D,2))

original array: 
 [[39 88 71 89]
 [28 11 65 86]
 [37 90 28 31]
 [55 98 60 19]]
new arrays: 
 [array([[39, 88, 71, 89],
       [28, 11, 65, 86]]), array([[37, 90, 28, 31],
       [55, 98, 60, 19]])]


Create a 4*4 array of integers, which you "unfold" into a 1D vector using the reshape command. You will then use the shuffle and permutation commands to mix these numbers

In [27]:
ar=np.random.randint(100,size=(4,4))
print('original array: \n',ar)
ar1=np.reshape(ar,newshape=(1,16))
print('reshaped array: ',ar1)
np.random.shuffle(ar)
print('shuffled array: \n',ar)
print('permutated array: \n',np.random.permutation(ar))

original array: 
 [[62 68 98  1]
 [67 52 57 66]
 [65 22 18 12]
 [31 79 68 35]]
reshaped array:  [[62 68 98  1 67 52 57 66 65 22 18 12 31 79 68 35]]
shuffled array: 
 [[65 22 18 12]
 [31 79 68 35]
 [67 52 57 66]
 [62 68 98  1]]
permutated array: 
 [[31 79 68 35]
 [67 52 57 66]
 [62 68 98  1]
 [65 22 18 12]]


Merge a 3*3 matrix made of integers, with a vector of three elements, once horizontally, and once vertically

In [28]:
arM=np.random.randint(100,size=(3,3))

arM1=np.random.randint(100,size=(3,3))
arV=np.arange(4,7) #it doesn't work if the matrixes are not of the same dimensions
print('matrix 1: \n',arM)
print('matrix 2: \n',arM1)
print('horizonatally: \n',np.concatenate((arM,arM1), axis=1)) #horizontally
print('vertically',np.concatenate((arM,arM1), axis=0)) #vertically

matrix 1: 
 [[47  9 44]
 [84 23 23]
 [80 59 39]]
matrix 2: 
 [[94 17 30]
 [90 81 19]
 [92 92 92]]
horizonatally: 
 [[47  9 44 94 17 30]
 [84 23 23 90 81 19]
 [80 59 39 92 92 92]]
vertically [[47  9 44]
 [84 23 23]
 [80 59 39]
 [94 17 30]
 [90 81 19]
 [92 92 92]]


Demonstrate your mastery and understanding of the resize command, then the argsort command. Make comments

Write a NumPy program to get the n largest values ​​of an array, use np.partition and play with both positive and negative values ​​of n, the second argument of the function, before explaining in your words what is happening. pass

Sort a 2*2 array, on the one hand before having flattened it, and on the other hand after having flattened it

In [29]:
arr2D=np.array([[30,22],[50,15]])
print('array:\n',arr2D)
print(arr2D.flatten())
print('Flattened: \n',np.sort(arr2D))
print('without flattening:\n', np.sort(arr2D,axis=0))

array:
 [[30 22]
 [50 15]]
[30 22 50 15]
Flattened: 
 [[22 30]
 [15 50]]
without flattening:
 [[30 15]
 [50 22]]


Produce a 1D array of the size of your choice, containing a random number of 2 between 5 and 10. Count the number of times the value 2 is repeated in the array.

In [63]:
array_of_rand=np.random.randint(5,11)
array_of_2s=np.random.choice([2],array_of_rand)
print('array of 2s:',array_of_2s)
print('hom many 2s: ', np.count_nonzero(array_of_2s==2))

array of 2s: [2 2 2 2 2 2 2 2]
hom many 2s:  8


Create an integer vector of size 30 with numbers between 1 and 12. Then use np.isin to check if the numbers 4, 6 and 7 appeared in the sequence

In [30]:
intVector=np.random.randint(1,high=12,size=30)
print('Vector:\n',intVector)
np.isin(intVector,[4,6,7])

Vector:
 [ 3  6  6  1  5  6 11  3  5  4 10  4  7  8  2  1  3  5 10 10  4  4  7 11
  5  3 11  4 10 11]


array([False,  True,  True, False, False,  True, False, False, False,
        True, False,  True,  True, False, False, False, False, False,
       False, False,  True,  True,  True, False, False, False, False,
        True, False, False])

**np.where**

Create an integer vector of size 30 with numbers between 1 and 12, then use the np.where function to identify indexes of numbers greater than 6

In [31]:
v=np.linspace(1,12,num=30,dtype=int)
print(v)
print(np.where(v>6)[0])

[ 1  1  1  2  2  2  3  3  4  4  4  5  5  5  6  6  7  7  7  8  8  8  9  9
 10 10 10 11 11 12]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29]


**Données manquantes**

Create an array of 3 * 3 and introduce a missing value at index [0,0], via np.nan

In [32]:
ar=np.random.rand(3,3)
ar[0,0]=np.nan
ar



array([[       nan, 0.07586912, 0.42056307],
       [0.85468547, 0.93035413, 0.85825894],
       [0.50528498, 0.29158342, 0.94690148]])

Transform this missing value into zero using np.fillna

In [33]:
np.nan_to_num(ar)

array([[0.        , 0.07586912, 0.42056307],
       [0.85468547, 0.93035413, 0.85825894],
       [0.50528498, 0.29158342, 0.94690148]])

You have two sets of integers: A = {1, 2, 3, 4, 5} and B = {3, 4, 5, 6, 7}. Write a program in Python using the appropriate function to find the union of these two sets and return the result.

In [34]:

A=np.array([1, 2, 3, 4, 5])
B=np.array([3, 4, 5, 6, 7])
print('A: ',A)
print('B: ',B)
np.union1d(A,B)

A:  [1 2 3 4 5]
B:  [3 4 5 6 7]


array([1, 2, 3, 4, 5, 6, 7])

You have two sets of integers: A = {1, 2, 3, 4, 5} and B = {3, 4, 5, 6, 7}. Write a program in Python using the appropriate function to find the intersection of these two sets and return the result

In [35]:
print('A: ',A)
print('B: ',B)
print('Intersection: ',np.intersect1d(A,B))

A:  [1 2 3 4 5]
B:  [3 4 5 6 7]
Intersection:  [3 4 5]


You have a set of integer values ​​= {2, 4, 6}, and a NumPy array = [1, 2, 3, 4, 5]. Write a program in Python using np.in1d ​​to check if each element in array belongs to the set values. The program must return an array of booleans indicating the membership of each element

In [36]:
set=np.array([2,4,6])
print('Array: ',A)
print('set: ',set)
np.in1d(A,set)

Array:  [1 2 3 4 5]
set:  [2 4 6]


array([False,  True, False,  True, False])

You have two sets of integers: A = {1, 2, 3, 4, 5} and B = {3, 4, 5, 6, 7}. Write a program in Python using np.setdiff1d to find elements that are in A but not in B, then return the result.

In [37]:
print('A: ',A)
print('B: ',B)
np.setdiff1d(A,B)

A:  [1 2 3 4 5]
B:  [3 4 5 6 7]


array([1, 2])

Write a function that takes a NumPy array as input and returns a new array containing the differences between consecutive elements of the input array. For example, if the input is [1, 3, 7, 11], the result should be [2, 4, 4].

In [38]:
def difference(array):
    new_array=np.zeros(array.size-1)
    for i in range(array.size-1):
        new_array[i]=array[i+1]-array[i]
    print(new_array)

difference(set)

[2. 2.]


**Calculus with NumPy**

Create a matrix of 4*4 real numbers, both negative and positive, then calculate for each row the sum, average, and cumulative sum

In [57]:
matr4=np.array([[1,2,3,5],[-1,5,3,-8],[5,-5,8,10],[-2,-3,-5,-6]])
print('matrix\n',matr4)
print('sum rows: ',np.sum(matr4,axis=1)) 
print('avarege: ',np.mean(matr4,axis=1))

matrix
 [[ 1  2  3  5]
 [-1  5  3 -8]
 [ 5 -5  8 10]
 [-2 -3 -5 -6]]
sum rows:  [ 11  -1  18 -16]
avarege:  [ 2.75 -0.25  4.5  -4.  ]


Repeat the previous operation by averaging the absolute values ​​of the numbers, then the minimum value and the maximum value; you will finally create a last column using the maximum value with the np.round function

In [59]:
abs_matr4=np.absolute(matr4)
print('abs matrix\n',abs_matr4)
print('sum rows: ',np.sum(abs_matr4,axis=1)) 
print('avarege: ',np.mean(abs_matr4,axis=1))
print('min_value: ',np.min(abs_matr4))
print('max_value: ',np.max(abs_matr4))


abs matrix
 [[ 1  2  3  5]
 [ 1  5  3  8]
 [ 5  5  8 10]
 [ 2  3  5  6]]
sum rows:  [11 17 28 16]
avarege:  [2.75 4.25 7.   4.  ]
min_value:  1
max_value:  10


Place 10 points randomly on a plane, then calculate the distance vectors between these different points. How many distance calculations do you do? Visualize points with matplotlib

Now visualize these distances on the plan, still with matplotlib

Create a list of randomly generated integers, and use np.mod (for modulo) to identify indexes of even numbers

In [40]:
randomarray=np.random.randint(100,size=5)
print(randomarray)
print(np.where(np.mod(randomarray,2)==0))


[62 38 10 21 36]
(array([0, 1, 2, 4], dtype=int64),)


**Fonctions universelles**

Take the vector {3,4,6,9} and use the add and multiply functions

In [56]:
print('vector 1\n',[3,4,6,9])
print('vector 2\n',[1,2,3,4])
print('add: ',np.add([3,4,6,9],[1,2,3,4]))
print('multiplication: ',np.multiply([3,4,6,9],[1,2,3,4]))

vector 1
 [3, 4, 6, 9]
vector 2
 [1, 2, 3, 4]
add:  [ 4  6  9 13]
multiplication:  [ 3  8 18 36]


Use multiply.outer on two vectors, and explain the nature of the corresponding operations

In [41]:
v1=[2,4]
v2=[1,2,3]
np.outer(v1,v2)

array([[ 2,  4,  6],
       [ 4,  8, 12]])

Apply the negative function to the array [2,3,5]

In [42]:
np.negative([2,3,5])

array([-2, -3, -5])

**Numpy and strings**

Merge two arrays each comprising two strings, using the np.char.add function

In [43]:
np.char.add('inter','net')

array('internet', dtype='<U8')

Use the np.char.join function to insert the symbol ";" into a 5-character string. between each letter

In [44]:
np.char.join(';','krasi')

array('k;r;a;s;i', dtype='<U9')

Use the np.char.upper function on the character string of your choice

In [45]:
np.char.upper('Krasi')

array('KRASI', dtype='<U5')

Use np.char.replace to demonstrate how to replace one string (in a sentence) with another

In [46]:
np.char.replace('the dog is happy','dog','cat')

array('the cat is happy', dtype='<U16')

Use np.char.split to split an array containing two sentences into as many elements as there are words in them

In [47]:
np.char.split('The day is hot. I will go to the beach.')

array(list(['The', 'day', 'is', 'hot.', 'I', 'will', 'go', 'to', 'the', 'beach.']),
      dtype=object)

Create an array containing three strings including a repeated pattern, common to the three elements. Use np.char.count to count the number of times this pattern is repeated

In [48]:
strA=np.array(['strr','krrp','rrlfrr'])
np.char.count(strA,'rr')

array([1, 1, 2])

Modify an array of length 5 by inserting elements, then removing some

In [49]:
strB=['cat','dog','bear','horse','mouse']
print(np.insert(strB,0,'a')) #to put in 0 position
print(np.delete(strB,3)) #to remove object after 3 position

['a' 'cat' 'dog' 'bear' 'horse' 'mouse']
['cat' 'dog' 'bear' 'mouse']


Write a NumPy program to add a border (padded with 0s) around an existing array. You need two layers of zeros all around

In [50]:

print('old;\n',matr4)
print('new\n',np.pad(matr4, pad_width=1, mode='constant', constant_values=0))

old;
 [[0.28024927 0.2281349  0.531691   0.46518578]
 [0.99727843 0.32807414 0.69625097 0.50294832]
 [0.08620606 0.17490368 0.23498642 0.16188748]
 [0.85202185 0.63836983 0.97439916 0.14067864]]
new
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.28024927 0.2281349  0.531691   0.46518578 0.        ]
 [0.         0.99727843 0.32807414 0.69625097 0.50294832 0.        ]
 [0.         0.08620606 0.17490368 0.23498642 0.16188748 0.        ]
 [0.         0.85202185 0.63836983 0.97439916 0.14067864 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Write a NumPy program to create a 5x5 array with random values ​​and normalize it by row

In [51]:

an_array=np.random.randint(100,size=(5,5))
print('original\n',an_array)
sum_of_rows = an_array.sum(axis=1)
normalized_array = an_array / sum_of_rows[:, np.newaxis]

print(normalized_array)

original
 [[90 40 65 72 17]
 [ 5 85 71 37 64]
 [28 11 19 64 93]
 [63 58 93 49 16]
 [24 61 27 78 63]]
[[0.31690141 0.14084507 0.22887324 0.25352113 0.05985915]
 [0.01908397 0.32442748 0.27099237 0.14122137 0.24427481]
 [0.13023256 0.05116279 0.08837209 0.29767442 0.43255814]
 [0.22580645 0.2078853  0.33333333 0.17562724 0.05734767]
 [0.09486166 0.24110672 0.10671937 0.3083004  0.24901186]]


**Pour aller plus loin que la simple maîtrise des fonctions Numpy** (ChatGPT interdit)

Nous vous proposons quelques exercices de programmation, pour aller au-delà de la simple connaissance de fonctions

*Exercice 1*

Si le produit de deux nombres entiers est égal ou inférieur à 1 000, renvoyez le produit ; sinon, renvoyez leur somme. Nous attendons de vous que vous construisiez une fonction. numéro1 = 20,
nombre2 = 30, la sortie est 600

In [52]:
def productof(num1,num2):
    result=num1*num2
    if result<=1000:
        print(result)
    else: print(num1+num2)
productof(200,30)


230


*Exercice 2*

Créez un programme qui invite l'utilisateur à saisir une chaîne, puis affiche
les caractères situés à des positions d'index paires. Par exemple, si la chaîne est
"exemple", le programme doit afficher les caractères "x", "m", "l".

*Exercice 3*

Créez un programme qui prend une chaîne en entrée et supprime les caractères de
le début de la chaîne jusqu'à un index spécifié, ce qui donne une nouvelle chaîne.
Par exemple, si nous appelons la fonction remove chars(”example”, 3), la sortie
devrait être « mple ». Notez que l'index spécifié, noté 'n', doit être inférieur à la longueur de
la chaîne.

*Exercice 4*

Itérer la liste de nombres donnée et imprimer uniquement les nombres divisibles
par 5:  la liste donnée est [10, 20, 33, 46, 55] Divisible par 5 : 10, 20, 55

*Exercice 5*

Développer un programme qui détermine le nombre d'occurrences de la sous-chaîne
"Emma" dans une chaîne donnée.
• Donné : « Emma est une bonne développeuse. Emma est institutrice. »
• Résultat attendu : Emma est apparue 2 fois
Faites-le une fois avec la méthode « count » de chaîne, une fois sans.

*Exercice 6*

Écrivez un programme pour vérifier si le nombre donné est un nombre palindrome.
Un nombre palindrome est un nombre qui est le même après l'inverse. Par exemple
545, ce sont les nombres palindromes
Production attendue:
• numéro original 121 : Oui. le nombre donné est le numéro du palindrome
• numéro d'origine 125 : le numéro donné n'est pas un numéro palindrome

*Exercice 7*

Écrivez une boucle while pour afficher chaque caractère d'une chaîne et, si un caractère est
numéro : arrêter la boucle.